title: The Open CS Library
description: >-
  The Open CS Library is a collaborative project to make textbooks, references, solution manuals and
  other resources freely available for students who are currently pursuing the following
  courses (or their equivalents) at university.
baseurl: /openlib.cs
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md


collections:
  courses:
      output: true
      permalink: /:collection/:name

defaults:
    -
        scope:
            path: ""
            type: "courses"
        values:
            layout: course